import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <NextTopLoader
          color="#d52245"
          initialPosition={0.03}
          crawlSpeed={150}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease-out"
          speed={180}
          shadow="0 0 8px #d52245, 0 0 3px #d52245"
          zIndex={9999}
        />
        {children}
        <Toaster position="bottom-right" richColors />
      </body>
    </html>
  );
}
